version: '3.7'

services:
  php:
    build: ./${PHP_VERSION}
    container_name: php
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:9000:9000'
    links:
      - mysql
      - memcached
    networks:
      - bitrix
    restart: always
  web_server:
    build: ./${WEB_SERVER_TYPE}
    container_name: webserver
    depends_on:
      - source
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:80:80'
      - '${INTERFACE}:443:443'
    links:
      - php
    networks:
      - bitrix
    restart: always
  mysql:
    build: ./db/mysql
    container_name: mysql
    volumes_from:
      - "database/mysql:"
    ports:
      - '${INTERFACE}:3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: mysqld --sql-mode=""
    networks:
      - bitrix
    restart: always
  memcached:
    image: memcached:1.5-alpine
    container_name: memcached
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:11211:11211'
    networks:
      - bitrix
    restart: always
  source:
    image: alpine:latest
    container_name: source
    volumes:
      - logs:/var/log/${WEB_SERVER_TYPE}
      - logs:/var/log/php
      - logs:/var/log/mysql
      - logs:/var/log/memcached
      - mysql-db:/var/lib/mysql
      - memcached:/var/lib/memcached
      - ./www/html:/var/www/html
      - ${SITE_PATH}:/var/www/bitrix
      - /etc/localtime:/etc/localtime/:ro
    networks:
      - bitrix-dev-env
networks:
  bitrix-dev-env:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/24
volumes:
  mysql-db:
    - ./data/db/mysql
  memcached:
    - ./data/db/memcached
  logs:
    - ./data/logs
  tmp:
    - ./data/tmp