version: '3.7'

services:
  nginx:
    build: ./webserver/nginx
    container_name: nginx
    depends_on:
      - php
    ports:
      - '80:80'
      - '443:443'
    expose:
      - "9001"
      - "9000"
    volumes:
      - ./data/logs/nginx/:/var/log/nginx
      - ./app/:/app
    networks:
      - bitrix-dev-env
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        - X_DEBUG_REMOTE_HOST=127.0.0.1
        - X_DEBUG_PROFILER_ENABLE=true
    container_name: php
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - bitrix-dev-env
    volumes:
      - ./../:/app
#  source:
    #image: alpine:latest
    #container_name: source
      #volumes:
      #- ./data/logs/php/:/var/log/php
      #- ./data/logs/mysql/:/var/log/mysql
      #- ./data/logs/memcached/:/var/log/memcached
      #- ./data/db/mysql/:/var/lib/mysql
    #- ./data/db/memcached/:/var/lib/memcached
      #networks:
    #- bitrix-dev-env
networks:
  bitrix-dev-env:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/24